Update repo structure
UBC-MDS/DSCI-532_2024_19_food-price-tracker pull request #6
Opened 2024-03-26 02:24 UTC by JohnShiuMK

- updated structure to align the requirement: https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group19/blob/master/milestone1.md#4-repository-structure
 - added python-semantic-release github action, that we learn from 524 and I would like to try if it will work here 😀

2024-03-26 17:56 UTC, srfrew requested changes
Review complete! A few details to be added for repo structure and specific files, see individual comments. Looks great otherwise

2024-03-26 17:56 UTC, srfrew commented on README.md
Requirements here are for a project title and summary of purpose. 
I recommend adding TODO for installation until next week.

2024-03-26 17:56 UTC, srfrew commented on CONTRIBUTING.md
> +## Get Started!
We do not have installation instructions at this point. Better to replace with "TODO" for the time being.

2024-03-26 17:56 UTC, srfrew commented on CONTRIBUTING.md
Attribution for the template required at the bottom of this file.

2024-03-26 17:56 UTC, srfrew commented on LICENSE
>  MIT License
A non-software license (such as a CC-BY) is needed here to cover non-software content.

2024-03-26 17:56 UTC, srfrew commented on README.md
> +## License
Update license for non-software portions as recommended in license file comment

2024-03-26 17:56 UTC, srfrew commented on environment.yml
file needs basic packages to be initialized
(dashboard, data wrangling, visualization, version numbers, jupyter-nb compatibility for development)

2024-03-26 17:56 UTC, srfrew commented on .github/workflows/ci-cd.yml
> +          python-version: "3.9"
What python version are we going to use? Here is defaulted as 3.9. 
Could move up to 3.12 if desired, but 3.9 is still supported till 2025

2024-03-26 18:00 UTC, JohnShiuMK commented
appreciated for the review, @srfrew 
I will update them soon

2024-03-27 04:11 UTC, srfrew approved these changes
All changes match or improve on requested changes, looks awesome!
Approved

2024-03-27 04:15 UTC, merged